name: check-pull-request

on: [pull_request]

jobs:
  run:
    runs-on: self-hosted
    steps:
    - id: check-pr
      name: Check PR
      uses: moevm/pull-requests-checker@main
      with:
        github-token: ${{ github.token }}
        number-of-pr: ${{ github.event.number }}
        repository-name: ${{ github.event.repository.full_name }}
        author: ${{ github.event.sender.login }}

    - id: linter
      name: Check code style
      uses: moevm/pull-requests-checker@linter
      with:
        github-token: ${{ github.token }}
        number-of-pr: ${{ github.event.number }}
        repository-name: ${{ github.event.repository.full_name }}
